version: "3.9"

services:
  localtunnel:
    container_name: https_tunnel
    image: node:alpine
    command: npx localtunnel --port 4010 --local-host nindo_server
    depends_on:
      - cn-app-server

